[package]
name = "spark-ui"
version = "0.0.1"
description = "星火云AI"
authors = ["wangdiankun"]
edition = "2021"

# 默认二进制名称与 tauri.conf.json 的 productName 保持一致
[[bin]]
name = "星火云AI"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# 释放包体积优化
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
