spring:
  profiles:
    active: @package.env@
  autoconfigure:
    exclude:
      - org.flowable.spring.boot.ProcessEngineAutoConfiguration
      - org.flowable.spring.boot.ProcessEngineServicesAutoConfiguration
      - org.flowable.spring.boot.eventregistry.EventRegistryAutoConfiguration
      - org.flowable.spring.boot.eventregistry.EventRegistryServicesAutoConfiguration
      - org.flowable.spring.boot.FlowableSecurityAutoConfiguration