<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.spark</groupId>
        <artifactId>spark</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <name>spark-web</name>
    <description>spark-web 该模块用于提供web服务</description>
    <artifactId>spark-web</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.spark</groupId>
            <artifactId>spark-manage</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.spark</groupId>
            <artifactId>spark-kb</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.spark</groupId>
            <artifactId>spark-kg</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.spark</groupId>
            <artifactId>spark-llm</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.spark</groupId>
            <artifactId>spark-flow</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.spark</groupId>
            <artifactId>spark-chat</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.spark</groupId>
            <artifactId>spark-form</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.spark</groupId>
            <artifactId>spark-task</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <!-- hutool工具包 -->
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <!-- 配置环境的profile-->
    <profiles>
        <profile>
            <id>local</id>
            <properties>
                <!--打包环境-->
                <package.env>local</package.env>
                <!--日志存储路径-->
                <log.path>D:\\opt\\spark\\logs</log.path>
                <log.pattern>%d{HH:mm:ss.SSS} [%thread] [%X{UserId}] [%X{TrackId}] %-5level %logger{36} - %msg%n</log.pattern>
                <!--格式化输出：%d表示日期，%thread表示线程名，%-5level：级别从左显示5个字符宽度%msg：日志消息，%n是换行符-->
                <!--<log.pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</log.pattern>-->
            </properties>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <!--打包环境-->
                <package.env>prod</package.env>
                <!--日志存储路径-->
                <log.path>/opt/spark/logs</log.path>
                <!--格式化输出：%d表示日期，%thread表示线程名，%-5level：级别从左显示5个字符宽度%msg：日志消息，%n是换行符-->
                <log.pattern>%d{HH:mm:ss.SSS} [%thread] [%X{UserId}] [%X{TrackId}] %-5level %logger{36} - %msg%n</log.pattern>
                <!--<log.pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</log.pattern>-->
            </properties>
        </profile>
    </profiles>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <!-- 启用属性替换 -->
                <filtering>true</filtering>
            </resource>
        </resources>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>

        <!-- 指定jar包名称 -->
        <finalName>spark-${project.version}</finalName>
    </build>
</project>