/**
 * 基础组件配置
 */
export const basicWidgetList = [
    {
        type: 'input',
        name: '单行文本',
        config: {
            code: '',
            label: '单行文本',
            required: false,
            width: 12,
            value: null,
            showValue: null,
            placeholder: '请输入',
            readonly: false,
            disabled: false,
            hidden: false,
        },
    },
    {
        type: 'textarea',
        name: '多行文本',
        config: {
            code: '',
            label: '多行文本',
            required: false,
            width: 12,
            value: null,
            showValue: null,
            placeholder: '请输入',
            readonly: false,
            disabled: false,
            hidden: false,
        },
    },
    {
        type: 'radio',
        name: '单选框',
        config: {
            code: '',
            label: '单选框',
            required: false,
            width: 12,
            value: null,
            showValue: null,
            disabled: false,
            hidden: false,
            options:[
                { value: '1', label: '选项 1' },
                { value: '2', label: '选项 2' },
            ],
        },
    },
    {
        type: 'select',
        name: '下拉选择',
        config: {
            code: '',
            label: '下拉选择',
            required: false,
            width: 12,
            value: null,
            showValue: null,
            placeholder: '请选择',
            disabled: false,
            hidden: false,
            options:[
                { value: '1', label: '选项 1' },
                { value: '2', label: '选项 2' },
            ],
        },
    },
    {
        type: 'number',
        name: '计数器',
        config: {
            code: '',
            label: '计数器',
            required: false,
            width: 12,
            value: null,
            showValue: null,
            min: 0,
            max: 100,
            step: 1,
            disabled: false,
            hidden: false,
        },
    },
    {
        type: 'date',
        name: '日期',
        config: {
            code: '',
            label: '日期',
            required: false,
            width: 12,
            value: null,
            showValue: null,
            placeholder: '请选择日期',
            dateType: 'date',
            readonly: false,
            disabled: false,
            hidden: false,
        },
    },
]

export const sysWidgetList = [
    {
        type: 'select-user',
        name: '选择用户',
        config: {
            code: '',
            label: '选择用户',
            required: false,
            width: 12,
            value: null,
            showValue: null,
            placeholder: '请选择用户',
            disabled: false,
            hidden: false,
            multiple: false,
        },
    },
    {
        type: 'select-dept',
        name: '选择部门',
        config: {
            code: '',
            label: '选择部门',
            required: false,
            width: 12,
            value: null,
            showValue: null,
            placeholder: '请选择部门',
            disabled: false,
            hidden: false,
            multiple: false,
        },
    },
    {
        type: 'select-role',
        name: '选择角色',
        config: {
            code: '',
            label: '选择角色',
            required: false,
            width: 12,
            value: null,
            showValue: null,
            placeholder: '请选择角色',
            disabled: false,
            hidden: false,
            multiple: false,
        },
    },
    {
        type: 'upload-attachment',
        name: '上传附件',
        config: {
            code: '',
            label: '上传附件',
            required: false,
            width: 12,
            value: null,
            showValue: null,
            disabled: false,
            hidden: false,
            multiple: false,
            downloadable: true,
        },
    }
]